---
Name: maxime-rainville-silverstripe-db-json
after:
  name: '#databaseconnectors'
---
SilverStripe\Core\Injector\Injector:
  MySQLSchemaManager:
    class: MaximeRainville\Silverstripe\DbJson\MySQL8SchemaManager

SilverStripe\ORM\DataObject:
  extensions:
    - MaximeRainville\Silverstripe\DbJson\JsonDataExtension


---
Name: maxime-rainville-silverstripe-db-json-databaseconnectors
after:
  name: '#coresearchfilters'
---
SilverStripe\Core\Injector\Injector:
  DataListFilter.Json:
    class: MaximeRainville\Silverstripe\DbJson\JsonFilter
  JsonFilter: '%$DataListFilter.Json'
