name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      dynamic_matrix: false
      extra_jobs: |
        - php: '8.1'
          db: mysql80
          phpunit: true
          composer_require_extra: "silverstripe/installer:^4"
        - php: '8.2'
          db: mysql80
          phpunit: true
          composer_require_extra: "silverstripe/installer:^5"
        - php: '8.2'
          db: mariadb
          phpunit: true
          composer_require_extra: "silverstripe/installer:^5"
